### ISSUE TITLE
taint core/minidump

### ISSUE THREAD

**Issue by s0i37** [chase1635321/r2taint#1]
Hello.
I was so excited of your implementation of static taint execution with BAP! Thank you for good example of usage BAP tool.
Half year ago I implemented very similar tool for taint `https://github.com/radareorg/radare2-extras/tree/master/r2taint` with ESIL emulation.
I like your implementation because of you use special tool for this - BAP. But how can I use it for analysis corefile/minidump or another abstract formats?
Thank you.

**Comment by 0xchase** [comment]
Hello @s0i37

Unfortunately, I haven't attempted to use this plugin for those applications. The plugin is pretty hacky, it just calls BAP as a subprocess and searches stdout. In principle it should work on any file that BAP knows how to lift, but I'm not sure if BAP knows how to lift a minidump or not... if it can't then you'll have to talk to them. If BAP can lift these files but the plugin still doesn't work, then you'll probably need to adjust the command line parameters in the subprocess call.

**Comment by s0i37** [comment]
Ok. Thanks.
I asked question to BAP developers.
